---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: graphicviolence
    labels:
        app: graphicviolence
spec:
    replicas: 1
    selector:
        matchLabels:
            app: graphicviolence
    template:
        metadata:
            labels:
                app: graphicviolence
        spec:
            volumes:
              - name: static-content
                emptyDir: {}        
            containers:
              - name: frontend
                image: nginx:1.17
                ports:
                  - containerPort: 80
                volumeMounts:
                  - name: static-content
                    mountPath: /usr/share/nginx/html

              - name: git-sync
                image: openweb/git-sync:0.0.1
                volumeMounts:
                  - name: static-content
                    mountPath: /static-content
                env:
                  - name: GIT_SYNC_REPO
                    value: "https://github.com/roelvanduijnhoven/graphicviolence-in-memoriam.git"
                  - name: GIT_SYNC_DEST
                    value: "/static-content"
                  - name: GIT_SYNC_WAIT
                    value: "600"